openapi: 3.0.0
info:
  title: OPEN-ARC CHATS APIS
  description: Open-Arc Project Rest API'S Chat related
  version: 0.1.9
servers:
  - url: http://127.0.0.1:5004
    description: Local server
  - url: http://ec2-3-15-1-100.us-east-2.compute.amazonaws.com:5004
    description: Droplet server
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
paths:
  /ChatMessages/{user_id}:
    post:
      security:
        - bearerAuth: []
      summary: Get all chat messages of a user
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: Numeric ID of the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sent_to:
                  type: string
                  description: user id whose messages you want to see
      responses: 
        '200':
          description: All chat messages
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Server Error